"""Add duration_ms and model_version to PredictionLog

Revision ID: 4a23cd1488be
Revises: 338560c40398
Create Date: 2026-05-29 08:45:15.539311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a23cd1488be'
down_revision: Union[str, Sequence[str], None] = '338560c40398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_logs', sa.Column('duration_ms', sa.Float(), nullable=True))
    op.add_column('prediction_logs', sa.Column('model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction_logs', 'model_version')
    op.drop_column('prediction_logs', 'duration_ms')
    # ### end Alembic commands ###
